### ISSUE TITLE
Seg fault with improper arguments

### ISSUE THREAD

**Issue by twrightsman** [lh3/miniprot#4]
I accidentally used the `-d` option while attempting to do alignment and `miniprot` segfaulted instead of printing an error message.

```
$ miniprot --version
0.2-r116
$ miniprot -t8 -d genome.mpi query.faa.gz > aln.paf
[M::mp_ntseq_read@0.192*1.01] read 20843494 bases in 48265 contigs
[M::mp_idx_build@0.192*1.01] 210726 blocks
[M::mp_idx_build@0.332*3.88] collected syncmers
Segmentation fault
```

**Comment by lh3** [comment]
Thanks. Fully agree that miniprot should report an error rather than segfault. Will have a look.

**Comment by lh3** [comment]
Miniprot doesn't segfault now. However, it will parse proteins as if they are nucleotide sequences without outputting errors. Checking proteins vs nucleotides requires more work.

**Comment by silviaprietob** [comment]
Hello!
I think I might be having a similar issue to the one twrightsman had.
I accidentally used -gff instead of --gff when running miniprot, and now every time I try to run it with the correct option, miniprot returns a 'unrecogniszed option' and a Segmentation fault (core dumped) error.

`$ miniprot/miniprot -I --gff -outs=0.95 miniprot/genomicfastas/PHYGR.fa missingfastas/PHYGRmissing.fa > miniprotout/PHYGR.gff

[WARNING] unrecognized option: --gff
[M::mp_ntseq_read@2.887*0.98] read 1373559025 bases in 460 contigs
[M::mp_idx_build@2.887*0.98] 10731402 blocks
Segmentation fault (core dumped)`

I don't think it's the memory either as I have given it up to 50 G.

Any ideas as to why this might be, how to fix it?

Thank you very much!
